import type { Metadata } from "next";
import AppHeader from "@/components/app.header";
import AppFooter from "@/components/app.footer";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/homepage.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
